---
title: "Final"
author: "Samuel Lane & Nolan Scott"
format: 
  dashboard: 
    theme: sandstone
embed-resources: true

---

```{r}
#| warning: false
#| message: false
library(tidyverse)
library(fmsb)

climbs = read_csv("Climbs.csv", col_select = c(1, 2, 3, 4, 5, 6, 8, 11, 14, 15, 
                                               16, 17, 26, 28, 32, 34), 
na = c("NA", "", "N/A", "Don't know", "?", "??", "???", "Na", "unknown", 
       "Not sure", "no idea", "Unsure", "Not sure", "Nil", "Dont know",
       "don't know", "Dunno", "????", "No clue", "i suck!", "N/a", 
       "oooh...not sure", "ha! no need to train that yet", 
       "Never tried this", "Not calculated before", "n/a", "-", 
       " I don't know", "idk", "I don't climb routes", "I don't boulder"))


colnames(climbs) = c("time", "sex", "height", "weight", "arm_span", 
"time_climbed", "max_grade_boulder", "max_grade_sport", "frequency_climbing", 
"avg_hours_climbing_week", "avg_hours_training_week", "frequency_hangboarding", 
"frequency_endurance", "frequency_strength", "max_pullup", "max_pushup")

climbs = climbs |> mutate(
  height = as.numeric(parse_number(height)),
  weight = as.numeric(parse_number(weight)),
  arm_span  = as.numeric(parse_number(arm_span)),
  max_grade_boulder  = as.integer(parse_number(max_grade_boulder)),
  max_grade_sport  = as.integer(max_grade_sport),
  frequency_climbing  = as.integer(frequency_climbing),
  avg_hours_climbing_week  = as.integer(avg_hours_climbing_week),
  avg_hours_training_week  = as.integer(avg_hours_training_week),
  frequency_hangboarding  = as.integer(frequency_hangboarding),
  frequency_endurance  = as.integer(frequency_endurance),
  frequency_strength  = as.integer(frequency_strength),
  max_pullup  = as.integer(parse_number(max_pullup)),
  max_pushup  = as.integer(parse_number(max_pushup))
)
```

# Introduction
To see our dashboard which is how it is meant to be viewed go to this link 

https://samrlane.github.io/STAT408_Final

A link to our Github repository

https://github.com/SamRLane/STAT408_Final

# Results 1

```{r}
#| warning: false
#Had to look up code for IQR to remove outliers
climbsAH = climbs |> filter(
  arm_span >= quantile(arm_span, 0.25, na.rm = TRUE) - 1.5 * IQR(arm_span, na.rm = TRUE), 
  arm_span <= quantile(arm_span, 0.75, na.rm = TRUE) + 1.5 * IQR(arm_span, na.rm = TRUE),
  height >= quantile(height, 0.25, na.rm = TRUE) - 1.5 * IQR(height, na.rm = TRUE), 
  height >= quantile(height, 0.75, na.rm = TRUE) - 1.5 * IQR(height, na.rm = TRUE)
)
#arm span vs max grade bouldering
ggplot(data = climbsAH, aes(x = arm_span, y = max_grade_boulder), na.rm = TRUE) + 
  geom_smooth()
#ape index vs max grade bouldering
ggplot(data = climbsAH, aes(x = arm_span - height, y = max_grade_boulder)) + 
  geom_smooth()
```

# Results 2

```{r}
#| warning: false

climbsP = climbs |> filter(
  max_pullup >= quantile(max_pullup, 0.25, na.rm = TRUE) - 1.5 * IQR(max_pullup, na.rm = TRUE), 
  max_pullup <= quantile(max_pullup, 0.75, na.rm = TRUE) + 1.5 * IQR(max_pullup, na.rm = TRUE),
  max_pushup >= quantile(max_pushup, 0.25, na.rm = TRUE) - 1.5 * IQR(max_pushup, na.rm = TRUE), 
  max_pushup <= quantile(max_pushup, 0.75, na.rm = TRUE) + 1.5 * IQR(max_pushup, na.rm = TRUE)
)

#pullup + pushup vs max grade
ggplot(data = climbsP, na.rm = TRUE) + 
  geom_smooth(aes(x = max_pullup, y = max_grade_boulder)) +
  geom_smooth(aes(x = max_pushup, y = max_grade_boulder))
                

  ggplot(data = climbsP, na.rm = TRUE) + 
  geom_smooth(aes(x = max_pullup, y = max_grade_boulder)) +
  geom_smooth(aes(x = max_pushup, y = max_grade_boulder)) +
  xlim(0, 35)


```

```{r}

# Compute correlations of training variables with max_grade_boulder
training_vars <- c("frequency_climbing", "avg_hours_climbing_week", 
                   "avg_hours_training_week", "frequency_hangboarding",
                   "frequency_endurance", "frequency_strength",
                   "max_pullup", "max_pushup")

cors <- climbs |>
  select(max_grade_boulder, all_of(training_vars)) |>
  drop_na() |>
  summarise(across(all_of(training_vars),
                   ~cor(.x, max_grade_boulder, use = "complete.obs"))) |>
  round(3)

radar_data <- bind_rows(
  setNames(rep(list(1),  length(training_vars)), training_vars),  # max
  setNames(rep(list(0),  length(training_vars)), training_vars),  # min (was -1)
  cors
)

colnames(radar_data) <- c(
  "Sessions\n/week", "Hours\nclimbing", "Hours\ntraining",
  "Hangboard\nfreq", "Endurance\nfreq", "Strength\nfreq",
  "Max\npull-ups", "Max\npush-ups"
)

par(mar = c(1, 1, 2, 1), bg = "white")

radarchart(
  radar_data,
  axistype   = 1,
  pcol       = "#2171b5",
  pfcol      = adjustcolor("#2171b5", alpha.f = 0.25),
  plwd       = 2.5,
  cglcol     = "grey75",
  cglty      = 1,
  cglwd      = 0.6,
  axislabcol = "grey40",
  vlcex      = 0.85,
  calcex     = 0.7,
  caxislabels = c("0", "0.25", "0.5", "0.75", "1"),  # updated
  title      = "Correlation with max boulder grade"
)
```



# Summary

Stuff goes here

